# Generated by Django 5.0 on 2023-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='description',
            field=models.TextField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='students',
            name='nationality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='faculty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
