# Generated by Django 5.0 on 2023-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_students_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='nationality',
            field=models.BooleanField(default=False),
        ),
    ]
