# Generated by Django 5.0 on 2023-12-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_students_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='nationality',
        ),
    ]
