# Generated by Django 5.0 on 2023-12-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_students_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='nationality',
            field=models.BooleanField(default=False),
        ),
    ]
