# Generated by Django 5.0 on 2023-12-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_students_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stu_photo',
            field=models.FileField(default=None, upload_to='students_picture'),
        ),
    ]
