# Generated by Django 5.0 on 2023-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_students_stu_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stu_photo',
            field=models.ImageField(upload_to='students_picture'),
        ),
    ]
