# Generated by Django 5.0 on 2023-12-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_students_stu_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='stu_photo',
            new_name='stuimg',
        ),
    ]
