# Generated by Django 5.0 on 2023-12-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_students_stuimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stuimg',
            field=models.ImageField(upload_to='students_picture'),
        ),
    ]
