# Generated by Django 5.0 on 2023-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_students_stuimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
