# Generated by Django 5.0 on 2023-12-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_students_is_selected_alter_students_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.IntegerField(max_length=12),
        ),
    ]
