# Generated by Django 5.0 on 2023-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_alter_students_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
