# Generated by Django 5.0 on 2023-12-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_alter_students_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='stuimg',
        ),
    ]
