# Generated by Django 5.0 on 2023-12-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_remove_students_stuimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stuimg',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
    ]
