# Generated by Django 5.0 on 2023-12-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_students_stuimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stuimg',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
    ]
